// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../../../src/app/developer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/developer">> = Specific
  const handler = {} as typeof import("../../../../../src/app/developer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/kontak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kontak">> = Specific
  const handler = {} as typeof import("../../../../../src/app/kontak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/kpr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kpr">> = Specific
  const handler = {} as typeof import("../../../../../src/app/kpr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overview">> = Specific
  const handler = {} as typeof import("../../../../../src/app/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/ruko/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ruko">> = Specific
  const handler = {} as typeof import("../../../../../src/app/ruko/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/site-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site-plan">> = Specific
  const handler = {} as typeof import("../../../../../src/app/site-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/tipe-rumah/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tipe-rumah/[slug]">> = Specific
  const handler = {} as typeof import("../../../../../src/app/tipe-rumah/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../src/app/tipe-rumah/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tipe-rumah">> = Specific
  const handler = {} as typeof import("../../../../../src/app/tipe-rumah/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
