var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/tipe-rumah/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hqv0zd._.js")
R.c("server/chunks/ssr/_1e5j8xg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wie2sl._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/_197v8o-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_tipe-rumah_[slug]_page_actions_1a-s4c0.js")
R.m(94416)
module.exports=R.m(94416).exports
